add ci

diff --git a/.github/workflows/ScalaCI.yml b/.github/workflows/ScalaCI.yml
--- a/.github/workflows/ScalaCI.yml
+++ b/.github/workflows/ScalaCI.yml
@@ -4,17 +4,18 @@ on:
   push:
     branches:
       - master
+    tags: [ "*" ]
   pull_request:
     branches:
       - master
 
 jobs:
-  Java17:
+  build:
 
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v1
         with:
@@ -22,9 +23,42 @@ jobs:
 
       - name: Build
         run: sbt compile
-        
+
       - name: Check Style
-        run: sbt check   
-        
+        run: sbt check
+  
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Setup JDK
+        uses: actions/setup-java@v1
+        with:
+          java-version: 17
+
       - name: Test
-        run: sbt test  
+        run: sbt test
+  
+  #      - name: Run Test
+  #        if: success() || failure()
+  #        run: sbt coverage test
+  #
+  #      - name: Aggregate coverage report
+  #        run: sbt coverageAggregate
+  #
+  #      - name: Upload test coverage report
+  #        run: bash <(curl -s https://codecov.io/bash)
+
+  publish:
+    runs-on: ubuntu-20.04
+    needs: [ check ]
+    if: github.event_name != 'pull_request'
+    steps:
+      - name: Checkout current branch
+        uses: actions/checkout@v3.3.0
+        with:
+          fetch-depth: 0
+      - name: Setup JDK
+        uses: actions/setup-java@v1
+        with:
+          java-version: 17     
